### ISSUE TITLE
Тестовое задание Унософт

### ISSUE THREAD

**Issue by mary-grigoriiva** [Sergei8888/VkAnalyzer#3]
Добрый день, Сергей. Появилось новое замечание: не удается авторизоваться в приложении

**Comment by Sergei8888** [comment]
Пожалуйста, опишите проблему подробнее. Приложите скриншоты или подробное описание, что бы я смог ее исправить

**Comment by mary-grigoriiva** [comment]
Конечно) Я перехожу по ссылке на демо проект (в режиме инкогнито) -> появляется форма авторизации в вк -> выбираю продолжить как Мария - в консоли появляется ошибка авторизации

![image](https://github.com/Sergei8888/VkAnalyzer/assets/149430804/e6da65aa-975d-47db-9039-2cf49dcbe8a3)

**Comment by Sergei8888** [comment]
Авторизация в вк производится при помощи third party cookies, которые по умолчанию запрещены в режиме инкогнито. К сожалению, пользоваться сервисом из режима инкогнито нельзя, так как в этом режиме запрещена передача информации о вас от любых третьих лиц, включая вк.
